describe('공유 리소스 관리', function() {
    
    it('css를 저장 및 적용 할 수 있다.', function(){
        cy.visit('/')
        cy.get('button[name="react"]').click()
        cy.get('#css').click()
        cy.get(".ace_text-input").type('.main {{} margin: 5px; }', {force:true})
        cy.get('button').eq(0).click()
        cy.get('#property').click()
        cy.get('input').eq(0).type('main')
        cy.get('#design > div > div').should('have.css', 'margin', '5px')    
    })

    it('css를 수정 할 수 있다.', function(){
        cy.visit('/')
        cy.get('button[name="react"]').click()
        cy.get('#css').click()
        cy.get(".ace_text-input").type('.main {{} margin: 5px; }', {force:true})
        cy.get('button').eq(0).click()
        cy.get('#property').click()
        cy.get('input').eq(0).type('main')
        cy.get('#design > div > div').should('have.css', 'margin', '5px')    
        cy.get('#css').click()
        cy.get('#sidebar').find('div').eq(24).click()
        cy.get(".ace_text-input:first").type('{selectall}{backspace}.main {{} margin: 10px; }', {force:true})
        cy.get('button').eq(0).click()
        cy.get('#design > div > div').should('have.css', 'margin', '10px')    
    })

    it('css를 삭제 할 수 있다.', function() {
        cy.visit('/')
        cy.get('button[name="react"]').click()
        cy.get('#css').click()
        cy.get(".ace_text-input").type('.main {{} margin: 5px; }', {force:true})
        cy.get('button').eq(0).click()
        cy.get('#property').click()
        cy.get('input').eq(0).type('main')
        cy.get('#design > div > div').should('have.css', 'margin', '5px')    
        cy.get('#css').click()
        cy.get('#sidebar').find('div').eq(24).click()
        cy.get('button').eq(1).click()
        cy.get('#design > div > div').should('have.css', 'margin', '0px')  
    })
})